language: minimal

install:
  - ./build/build.sh

script:
  - ./test/images_exist.sh
  - ./test/test.sh

deploy:
  - provider: script
    script: ./deploy/docker_hub_push.sh
    on:
      tags: true
    skip_cleanup: 'true'

  - provider: script
    script: ./deploy/docker_hub_push.sh
    on:
      branch: "master"
    skip_cleanup: 'true'
